# Generated by Django 3.2.16 on 2023-01-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='interest',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('hiking', 'hiking'), ('cycling', 'cycling'), ('skiing', 'skiing'), ('camping', 'camping'), ('Skydiving', 'Skydiving'), ('Ballooning', 'Ballooning'), ('Surfing', 'Surfing'), ('Swimming', 'Swimming'), ('Shopping', 'Shopping')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='nationality',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='city',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='country',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='description',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='facebook_url',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='instagram_url',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='postalcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='state',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
