# Generated by Django 4.1.5 on 2023-01-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist',
            old_name='interests',
            new_name='interest',
        ),
    ]
