# Generated by Django 4.1.4 on 2022-12-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_address_tourist_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='interest',
            field=models.CharField(choices=[('Sports', 'Sports'), ('hiking', 'hiking'), ('cycling', 'cycling'), ('skiing', 'skiing'), ('camping', 'camping'), ('Skydiving', 'Skydiving'), ('Ballooning', 'Ballooning'), ('Surfing', 'Surfing'), ('Swimming', 'Swimming'), ('Shopping', 'Shopping')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
