# Generated by Django 4.1.5 on 2023-01-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_programstable_agency_programstable_inscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelagency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
