# Generated by Django 4.1.5 on 2023-01-14 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tourist_image_tourist_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramsTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('nbinscriptions', models.IntegerField()),
                ('price', models.FloatField()),
                ('deadline', models.DateField()),
                ('capacity', models.IntegerField()),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('payment', models.CharField(choices=[('P', 'paid'), ('NP', 'not paid')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('ifLogged', models.BooleanField(default=False)),
                ('token', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='travelagency',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='travelagency',
            old_name='phone',
            new_name='postalcode',
        ),
        migrations.AddField(
            model_name='tourist',
            name='statut',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelagency',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelagency',
            name='country',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelagency',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelagency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
        migrations.CreateModel(
            name='ProgramsLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('datedebut', models.CharField(max_length=50)),
                ('datefin', models.CharField(max_length=50)),
                ('category', models.TextField(max_length=100)),
                ('details', models.TextField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programstable')),
            ],
        ),
    ]
