# Generated by Django 4.1.5 on 2023-01-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_programstable_user_rename_address_travelagency_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='statut',
        ),
    ]
