# Generated by Django 4.1.5 on 2023-01-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_programstable_inscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstable',
            name='payment',
        ),
        migrations.AlterField(
            model_name='tourist',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='interest',
            field=models.ManyToManyField(blank=True, to='api.interest'),
        ),
    ]
