# Generated by Django 4.1.5 on 2023-01-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_user_remove_tourist_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelagency',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='age',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='gender',
        ),
        migrations.AddField(
            model_name='travelagency',
            name='description',
            field=models.TextField(default='', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelagency',
            name='facebook_url',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelagency',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='instagram_url',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelagency',
            name='state',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
