# Generated by Django 4.1.5 on 2023-01-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_username_travelagency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagency',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
