# Generated by Django 4.1.5 on 2023-01-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_programstable_payment_alter_tourist_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstable',
            name='payment',
            field=models.CharField(choices=[('P', 'paid'), ('NP', 'not paid')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
