# Generated by Django 4.1.5 on 2023-01-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_programstable_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstable',
            name='payment',
        ),
    ]
