# Generated by Django 4.1.5 on 2023-01-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_programstable_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='programslocations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
